# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import list_files_pb2 as list__files__pb2


class ListFilesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFilesList = channel.unary_unary(
                '/ListFiles/GetFilesList',
                request_serializer=list__files__pb2.ListFilesRequest.SerializeToString,
                response_deserializer=list__files__pb2.ListFilesResponse.FromString,
                )


class ListFilesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetFilesList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ListFilesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFilesList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFilesList,
                    request_deserializer=list__files__pb2.ListFilesRequest.FromString,
                    response_serializer=list__files__pb2.ListFilesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ListFiles', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class ListFiles(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetFilesList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ListFiles/GetFilesList',
            list__files__pb2.ListFilesRequest.SerializeToString,
            list__files__pb2.ListFilesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
