# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import search_files_pb2 as search__files__pb2


class FileSearchServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchFiles = channel.unary_stream(
                '/FileSearchService/SearchFiles',
                request_serializer=search__files__pb2.FileSearchRequest.SerializeToString,
                response_deserializer=search__files__pb2.FileSearchResponse.FromString,
                )


class FileSearchServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SearchFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileSearchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchFiles': grpc.unary_stream_rpc_method_handler(
                    servicer.SearchFiles,
                    request_deserializer=search__files__pb2.FileSearchRequest.FromString,
                    response_serializer=search__files__pb2.FileSearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FileSearchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FileSearchService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SearchFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/FileSearchService/SearchFiles',
            search__files__pb2.FileSearchRequest.SerializeToString,
            search__files__pb2.FileSearchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
