# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: search_files.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12search_files.proto\"-\n\x11\x46ileSearchRequest\x12\x18\n\x10\x66ilename_pattern\x18\x01 \x01(\t\"*\n\x12\x46ileSearchResponse\x12\x14\n\x05\x66iles\x18\x01 \x01(\x0b\x32\x05.File\"&\n\x04\x46ile\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04\x66ile\x18\x02 \x01(\x0c\x32O\n\x11\x46ileSearchService\x12:\n\x0bSearchFiles\x12\x12.FileSearchRequest\x1a\x13.FileSearchResponse\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'search_files_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FILESEARCHREQUEST._serialized_start=22
  _FILESEARCHREQUEST._serialized_end=67
  _FILESEARCHRESPONSE._serialized_start=69
  _FILESEARCHRESPONSE._serialized_end=111
  _FILE._serialized_start=113
  _FILE._serialized_end=151
  _FILESEARCHSERVICE._serialized_start=153
  _FILESEARCHSERVICE._serialized_end=232
# @@protoc_insertion_point(module_scope)
